name: gps-test
on:
  push:
    branches: [test]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: test

      - name: Update yaml
        uses: gofeel8/yaml-update-action@main
        with:
          branch: test
          masterBranchName: test
          targetBranch: test
          valueFile: 'yaml/test.yaml'
          propertyPath: 'spec.rules.host'
          value: 'gps'
          commitChange: true

      - name: Commit git-ops
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'change'
          branch: test
          create_branch: true
